data:
  class_path: terratorch.datamodules.GenericNonGeoSegmentationDataModule
  init_args:
    allow_substring_split_file: true
    batch_size: 8
    check_stackability: true
    constant_scale: 1.0
    dataset_bands:
    - BLUE
    - GREEN
    - RED
    - NIR_NARROW
    - SWIR_1
    - SWIR_2
    drop_last: true
    embedding_input: false
    expand_temporal_dimension: false
    ignore_split_file_extensions: true
    img_grep: '*_merged.tif'
    label_grep: '*.mask.tif'
    means:
    - 0.049771
    - 0.068685
    - 0.076481
    - 0.214572
    - 0.204851
    - 0.146201
    no_data_replace: 0.0
    no_label_replace: -1
    num_classes: 2
    num_workers: 8
    output_bands:
    - BLUE
    - GREEN
    - RED
    - NIR_NARROW
    - SWIR_1
    - SWIR_2
    pca_step: 4
    pin_memory: false
    reduce_zero_label: false
    return_georeference: false
    rgb_indices:
    - 2
    - 1
    - 0
    stds:
    - 0.031063
    - 0.036317
    - 0.049595
    - 0.085017
    - 0.094316
    - 0.082628
    test_data_root: data\t2_prithvi_chips\data
    test_split: data\t2_prithvi_chips\splits\test.txt
    test_transform:
    - class_path: ToTensorV2
    train_data_root: data\t2_prithvi_chips\data
    train_split: data\t2_prithvi_chips\splits\train.txt
    train_transform:
    - class_path: albumentations.D4
    - class_path: ToTensorV2
    val_data_root: data\t2_prithvi_chips\data
    val_split: data\t2_prithvi_chips\splits\val.txt
deploy_config_file: true
model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    class_names:
    - Not burned
    - Burn scar
    freeze_backbone: false
    freeze_decoder: false
    freeze_head: false
    ignore_index: -1
    loss: ce
    lr: 0.001
    model_args:
      backbone: prithvi_eo_v2_300
      backbone_bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
      backbone_pretrained: false
      decoder: UNetDecoder
      decoder_channels:
      - 512
      - 256
      - 128
      - 64
      necks:
      - indices:
        - 5
        - 11
        - 17
        - 23
        name: SelectIndices
      - name: ReshapeTokensToImage
      - name: LearnedInterpolateToPyramidal
      num_classes: 2
    model_factory: EncoderDecoderFactory
    output_most_probable: true
    output_on_inference: prediction
    plot_on_val: false
    tiled_inference_on_testing: false
    tiled_inference_on_validation: false
out_dtype: int16
seed_everything: 2
trainer:
  accelerator: auto
  accumulate_grad_batches: 1
  barebones: false
  check_val_every_n_epoch: 1
  detect_anomaly: false
  devices: auto
  enable_autolog_hparams: true
  enable_progress_bar: true
  fast_dev_run: false
  inference_mode: true
  log_every_n_steps: 1
  logger: false
  max_epochs: 100
  max_steps: -1
  num_nodes: 1
  overfit_batches: 0.0
  precision: 16-mixed
  reload_dataloaders_every_n_epochs: 0
  strategy: auto
  sync_batchnorm: false
  use_distributed_sampler: true
